version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - .:/app
  app:
    depends_on:
      - db
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      DBHOST: db
      
# Names our volume
volumes:
  my-db:
