version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - .:/app
      
# Names our volume
volumes:
  my-db:
